name: Android UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Android Emulator and tests
      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: pixel_4
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -accel off -netdelay none -netspeed full
          script: |
            adb wait-for-device
            adb shell getprop sys.boot_completed
            echo "Emulator ready"
            pytest --html=reports/report.html --self-contained-html
      

      # 5. Upload pytest-html report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html
