name: Android UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Set up Java & Android SDK (emulator)
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: |
            echo "Emulator is running"
            # Start Appium in background
            npm install -g appium
            appium --log-level error &
            # Run tests once emulator + appium are ready
            pytest --html=reports/report.html --self-contained-html

      # 5. Upload pytest-html report
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: reports/report.html
